# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'APLYFT' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  rn_path = '../node_modules/react-native'
  pod 'yoga', path: "#{rn_path}/ReactCommon/yoga/yoga.podspec"
  pod 'React', path: rn_path, subspecs: [
  'Core',
  'RCTActionSheet',
  'RCTAnimation',
  'RCTGeolocation',
  'RCTImage',
  'RCTLinkingIOS',
  'RCTNetwork',
  'RCTSettings',
  'RCTText',
  'RCTVibration',
  'RCTWebSocket'
  ]
  # Pods for APLYFT
  pod 'Stripe'
  pod 'RNImageCropPicker', :path => '../node_modules/react-native-image-crop-picker'
  
  pod 'Firebase/Core'
  pod 'Firebase/Performance'
  pod 'Fabric'
  pod 'Crashlytics'
  
  pod 'RNFirebase', :path => '../node_modules/react-native-firebase/ios'
  pod 'react-native-mixpanel', :path => '../node_modules/react-native-mixpanel'
  
  target 'APLYFT-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'RNSoundRecorder', :path => '../node_modules/react-native-sound-recorder'

    pod 'RNFS', :path => '../node_modules/react-native-fs'

    pod 'RNSound', :path => '../node_modules/react-native-sound'

    pod 'react-native-calendar-events', :path => '../node_modules/react-native-calendar-events'

    pod 'RNShare', :path => '../node_modules/react-native-share'

  end

  target 'APLYFTTests' do
    inherit! :search_paths
    # Pods for testing
  end
  
  post_install do |installer|
      installer.pods_project.targets.each do |target|
          if target.name == "React"
              target.remove_from_project
          end
      end
  end

end
